---
Description: 'Amazon EKS Cluster'

Parameters:

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

  Project:
    Type: String

  VPC:
    Type: String

Resources:

  ClusterControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-ClusterControlPlaneSecurityGroup"
        - Key: Project
          Value: !Ref Project

  AWSServiceRoleForAmazonEKS:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      ResourcesVpcConfig: 
        SecurityGroupIds:
          - !Ref ClusterControlPlaneSecurityGroup
        SubnetIds: !Ref Subnets
      RoleArn: !GetAtt AWSServiceRoleForAmazonEKS.Arn
      Version: 1.14

Outputs:

  EKSClusterName:
    Value: !Ref EKSCluster
    Description: EKS ClusterName

  RoleArn:
    Description: The role that EKS will use to create AWS resources for Kubernetes clusters
    Value: !GetAtt AWSServiceRoleForAmazonEKS.Arn

  ClusterControlPlane:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Ref ClusterControlPlaneSecurityGroup