Description: 'Security Groups'

Parameters:
  Project:
    Type: String
    Description: Name of this project or app
  VPC:
    Type: String
    Description: VPCId to use

Resources:
  EKSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-EKSSecurityGroup"
        - Key: Project
          Value: !Ref Project

Outputs:

  EKSSecurityGroup:
    Description: Security group for the cluster control plane communication with worker nodes
    Value: !Ref EKSSecurityGroup 
